logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.43.32 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: Doromv # 用户名
    password: 123456 # 密码